### ISSUE TITLE
Caroussel design suggesties

### ISSUE THREAD

**Issue by joostf** [zenitba/FDNDStrandeiland#56]
- [ ] witruimte boven en onder de foto weghalen (foto beeldvullend maken)
- [ ] de hele slide klikbaar maken
- [ ] de buttons en indicatoren buiten de slides zetten
- [ ] een subtiele animation on scroll (scroll driven animations) toevoegen

**Comment by zenitba** [comment]
- [x] **Witruimte boven en onder de foto weghalen (foto beeldvullend maken)**:

   Ik heb de CSS voor de `.carousel-image` aangepast:
     ```css
     .carousel-image {
       width: 100%; /* De breedte van de afbeelding 100% maken */
       height: 100%; /* De lengte van de afbeelding 100% maken */
     }
     ```

- [x] **De hele slide klikbaar maken**:

   Ik heb de `<a>`-tag rond de `.carousel-item`-div gewikkeld om de hele slide klikbaar te maken:
     ```html
     <a href={`/overzicht/wens/${wish.id}`} class="carousel-item">
     ...
     </a>
     ```
Omdat de <a>-tag om de .carousel-item is gewikkeld, is de lay-out van de carousel niet zoals het was wanneer JavaScript is uitgeschakeld.

<img width="677" alt="Schermafbeelding 2024-04-04 om 12 49 38" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/8a67069a-5180-40a5-9b49-d584be268bec">

- [x] **De buttons en indicatoren buiten de slides zetten**:

   Ik heb de buttons en indicatoren naar buiten de `.carousel`-container verplaatst:
     ```html
     <!-- Vorige knop -->
     <a href="#" class="carousel-link left-arrow" on:click={scrollLeftOrRight} title="Vorige slide" hidden>
     ...
     </a>

     <!-- Carousel container -->
     <div class="carousel">
     ...
     </div>

     <!-- Volgende knop -->
     <a href="#" class="carousel-link right-arrow" on:click={scrollLeftOrRight} title="Volgende slide" hidden>
     ...
     </a>

     <!-- Carrousel indicator -->
     <div class="carousel-indicator" hidden>
     ...
     </div>
     ```

- [x]  **Een subtiele animatie toevoegen**:

   Ik heb een animatie op de `.carousel-item`-elementen toegevoegd:
     ```css
     @keyframes slideIn {
       0% {
         transform: translateX(-100%);
         opacity: 0;
       }
       100% {
         transform: translateX(0);
         opacity: 1;
       }
     }

     .carousel-item {
       ...
       animation: slideIn 1s forwards; /* Animatie toegevoegd aan de .carousel-item */
     }
     ```
Nog niet helemaal tevreden met de animatie, maar voor nu is het acceptabel als tijdelijke oplossing.

<img width="1000" alt="Schermafbeelding 2024-04-04 om 12 45 33" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/e16b9d3d-2910-4be7-b11f-6687c94eb792">

<img width="702" alt="Schermafbeelding 2024-04-04 om 12 51 59" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/b8cd898b-5473-4c79-8b83-d22cd843b3b6">
